name: Release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    name: build bithesis manual
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            apk add make msttcorefonts-installer fontconfig
            update-ms-fonts
            fc-cache -f
            make doc
      - name: Upload bithesis.pdf for later usage.
        uses: actions/upload-artifact@v3
        with:
          name: bithesis
          path: bithesis.pdf
      - name: Upload *.cls for later usage.
        uses: actions/upload-artifact@v3
        with:
          name: cls
          path: "*.cls"

    
  publish_templates:
    name: Publish ${{ matrix.template }}
    runs-on: ubuntu-latest
    needs: build

    strategy:
      matrix:
        template: [graduate-thesis, undergraduate-thesis, lab-report, paper-translation, presentation-slide, undergraduate-thesis-en]

    steps:
      - uses: actions/checkout@v2
      - name: Download bithesis.pdf
        uses: actions/download-artifact@v3
        with:
          name: bithesis
      - name: Copy manual to the template folder.
        run: cp bithesis.pdf ./templates/${{ matrix.template }}
      - name: Install zip
        uses: montudor/action-zip@v1
      - name: Zip files under ./${{ matrix.template }}
        run: zip -qq -r ./${{ matrix.template }}.zip ./${{ matrix.template }}
        working-directory: ./templates
      - name: Upload ${{ matrix.template }}.zip to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./templates/${{ matrix.template }}.zip
          asset_name: ${{ matrix.template }}.zip
          tag: ${{ github.ref }}

    
  publish_cls:
    name: Publish ${{ matrix.cls }}
    runs-on: ubuntu-latest
    needs: build

    strategy:
      matrix:
        cls: [bithesis, bitreport, bitbeamer]

    steps:
      - uses: actions/checkout@v2
      - name: Download *.cls
        uses: actions/download-artifact@v3
        with:
          name: cls
      - name: Upload ${{ matrix.cls }}.cls to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.cls }}.cls
          asset_name: ${{ matrix.cls }}.cls
          tag: ${{ github.ref }}
