name: Test

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            apk add make msttcorefonts-installer fontconfig
            update-ms-fonts
            fc-cache -f
            make test

  check_typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check spelling of bithesis.dtx
        uses: crate-ci/typos@master

  ensure_updated_cls:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: xu-cheng/texlive-action/full@v1
        name: Check there is nothing to diff.
        with:
          run: |
            apk add make git
            git config --global --add safe.directory /github/workspace

            make check-cls

  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
